In [ ]:
import numpy as np
a=np.array([[1,2],[3,4],[5,6]])
a[a[:,1]%2==0]
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
import numpy as np
a=np.array([[1,2],[3,4],[5,6]])
a[a%2==0]
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
import numpy as np
a=np.array([1,2,3,4,5,6])
mask=np.array([True,False,True,False,True,False])
print(a[mask]*10)

[10 30 50]


In [ ]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
b=np.array([10,20,30])
print(a+b.shape)


[[4 5 6]
 [7 8 9]]


In [ ]:
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([10,20,30])
print(a+b)

ValueError: operands could not be broadcast together with shapes (2,2) (3,) 

In [ ]:
import numpy as np
x=np.array(10)
x[x%2==0]*=2
print(x)

20


In [ ]:
import numpy as np
a=np.array([[1,2],[3,4],[5,6]])
mask=np.array([False,False,False])
print(a[mask])

[]


In [ ]:
import numpy as np
a=np.array((2,3))
b=np.array((3,))
print(a*b)

[6 9]


In [ ]:
import numpy as np
import builtins
a=np.array([10,20,30,40,50])
idx=np.array([4,0,4,1])
builtins.print(a[idx])

[50 10 50 20]


In [ ]:
import numpy as np

a=np.array([10,20,30,40,50])
idx=np.array([4,0,4,1])
print(a[idx])

TypeError: 'numpy.ndarray' object is not callable