In [ ]:
#NUMPY

import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
# numpy creating arrays

import numpy as np
arr=np.array((1,2,3,4,5,6))
print(arr)

[1 2 3 4 5 6]


In [ ]:
#0-D Arrays

import numpy as np
arr=np.array(23)
print(arr)

23


In [ ]:
#1-D Arrays

import numpy as np
arr=np.array((1,2,3,4,5,6))
print(arr)



[1 2 3 4 5 6]


In [ ]:
#2-D Arrays
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr)



[[1 2 3]
 [4 5 6]]


In [ ]:
#3-D Arrays
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[10,20,30],[40,50,60]]])
print(arr)



[[[ 1  2  3]
  [ 4  5  6]]

 [[10 20 30]
  [40 50 60]]]


In [ ]:
# number of dimensions

import numpy as np
a=np.array(23)
b=np.array((1,2,3,4,5,6))
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[[1,2,3],[4,5,6]],[[10,20,30],[40,50,60]]])


print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)




0
1
2
3


In [ ]:
#numpy array indexing

import numpy as np
arr=np.array([1,2,3,4])
print(arr[0])

1


In [ ]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr[2]+arr[3])

7


In [ ]:
arr=np.array([1,2,3,4,5,6])
arr_2d=np.array([[1,2,3],[4,5,6]])
zeros=np.zeros((3,4))
ones=np.ones((2,3))
range_arr=(0,10,2)
linspace=np.linspace(0,1,5)
identity=np.eye(3)
random_arr=np.random.rand(3,4)

print(zeros)
print(ones)
print(range_arr)
print(linspace)
print(identity)
print(random_arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
(0, 10, 2)
[0.   0.25 0.5  0.75 1.  ]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.21973978 0.76150052 0.70778087 0.12380903]
 [0.5369503  0.38513064 0.60726995 0.50357089]
 [0.69865174 0.13242698 0.06534247 0.28919875]]


In [ ]:
#numpy arry attributes and functions

#array creation

a=np.array([1,2,3])
print(a.shape)

(3,)


In [ ]:
a=np.array([[1,2,3],[4,5,6]])
print(a.shape)
print(a.dtype)
print(a.size)
print(a.ndim)
print(np.sum(a))
print(np.mean(a,axis=0))
print(np.mean(a,axis=1))
print(np.max(a))
print(np.min(a))


(2, 3)
int64
6
2
21
[2.5 3.5 4.5]
[2. 5.]
6
1


In [15]:
a=np.array([[[1,2,3],[4,5,6]],[[10,20,30],[40,50,60]]])


print(a.shape)
print(a.dtype)
print(a.size)
print(a.ndim)
print(np.sum(a))
print(np.mean(a,axis=0))
print(np.mean(a,axis=1))
print(np.max(a))
print(np.min(a))


(2, 2, 3)
int64
12
3
231
[[ 5.5 11.  16.5]
 [22.  27.5 33. ]]
[[ 2.5  3.5  4.5]
 [25.  35.  45. ]]
60
1


In [5]:
#1-D Arrays

import numpy as np
arr=np.array([1,2,3,4,5,6])
print(arr)



[1 2 3 4 5 6]


In [ ]:
# index pf extreme value
b=np.array([10,40,30])
print(np.argmin(b))
print(np.argmax(b))


0
1


In [ ]:
# agriculture application
import numpy as np
crop_yields=np.array([
    [12.3,13.5,14.5,15.5],
    [10.1,10.2,10.3,10.4],
    [15.1,15.2,15.3,15.4],
    [11.2,11.3,11.4,11.5]

])

print('crops yields array(tons):')
print(crop_yields)
print(f'\nshape:{crop_yields.shape}')
print(f'Data type:{crop_yields.dtype}')
print(f'Total elements:{crop_yields.size}')
print(f'Number of dimensions:{crop_yields.ndim}')

total_production = np.sum(crop_yields)
avg_yield_per_farm = np.mean(crop_yields,axis=1)
avg_yield_per_season = np.mean(crop_yields,axis=0)
max_yield = np.max(crop_yields)
min_yield = np.min(crop_yields)

print(total_production)
print(avg_yield_per_farm)
print(avg_yield_per_season)
print(max_yield)
print(min_yield)
print(f'\nTotal production:{total_production}tons')
print(f'averege per farm={avg_yield_per_farm}tons')
print(f'averege per season={avg_yield_per_season}tons')
print(f'maxium yield={max_yield}tons')
print(f'minimum yield={min_yield}tons')


crops yields array(tons):
[[12.3 13.5 14.5 15.5]
 [10.1 10.2 10.3 10.4]
 [15.1 15.2 15.3 15.4]
 [11.2 11.3 11.4 11.5]]

shape:(4, 4)
Data type:float64
Total elements:16
Number of dimensions:2
203.2
[13.95 10.25 15.25 11.35]
[12.175 12.55  12.875 13.2  ]
15.5
10.1

Total production:203.2tons
averege per farm=[13.95 10.25 15.25 11.35]tons
averege per season=[12.175 12.55  12.875 13.2  ]tons
maxium yield=15.5tons
minimum yield=10.1tons


In [3]:
import numpy as np

#locality of reference

my_array = np.arange(100)
total_sum = 0
for i in range(100):
    total_sum += my_array[i]

print(f"Total sum: {total_sum}")


Total sum: 4950


In [13]:
# number of dimensions

import numpy as np
a=np.array(23)
b=np.array((1,2,3,4,5,6))
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[[1,2,3],[4,5,6]],[[10,20,30],[40,50,60]]])
f=np.array([[1,2,3],[4,5,6]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)
print(f.ndim)

0
1
2
3
2
