In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
a=np.zeros(6)
b=np.ones(4)
c=np.arange(1,11)
d=np.linspace(0,100,5)
print(a,b,c,d)

[0. 0. 0. 0. 0. 0.] [1. 1. 1. 1.] [ 1  2  3  4  5  6  7  8  9 10] [  0.  25.  50.  75. 100.]


In [ ]:
import numpy as np
rainfall=np.array([120,95,160,140])
total_rainfall=np.sum(rainfall)
avgerage_rainfall=np.mean(rainfall)
print("Total Rainfall:",total_rainfall)
print("Average_rainfall:",avgerage_rainfall)

Total Rainfall: 515
Average_rainfall: 128.75


In [ ]:
a=[[1,2],[3,4]]
b=[[5,6],[7,8]]
result=[[[a[i][j]+b[i][j]]for j in range(2)]for i in range(2)]
print("matrix addition:")
for row in result:
  print(row)

matrix addition:
[[6], [8]]
[[10], [12]]


In [ ]:
A=[[1,2],[3,4]]
B=[[2,0],[1,2]]
result=[[0,0],[0,0]]
for i in range(2):
  for j in range(2):
    for k in range(2):
      result[i][j]+=A[i][k]*B[k][j]
print("matrix manipulation:")
for roe in result:
  print(roe)

matrix manipulation:
[4, 4]
[10, 8]


In [ ]:
A=[[1,2,3],[4,5,6]]
transpose=[[[A[j][i]] for j in range(len(A))]
for i in range(len(A[0]))]
print("transpose:")
for row in transpose:
  print(row)



transpose:
[[1], [4]]
[[2], [5]]
[[3], [6]]


In [ ]:
import numpy as np
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print(arr)
np.sort(arr)

[2 1 5 3 7 4 6 8]


array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
#numpy.argsort
import numpy as np
x = np.array([3, 1, 2])
np.argsort(x)

array([1, 2, 0])

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
C = np.array([9,10,11,12])
np.concatenate((a,b,c))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  1,  2,  3,  4,  5,  6,  7,  8,  9,
       10])

In [ ]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
np.concatenate((x, y))


array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
#arr.reshape()

a = np.arange(6)
print(a)
b = a.reshape(3, 2)
print(b)

[0 1 2 3 4 5]
[[0 1]
 [2 3]
 [4 5]]


In [ ]:
#arr.reshape()

a = np.arange(6)
print(a)
b = a.reshape(3,2)
print(b)

[0 1 2 3 4 5]
[[0 1]
 [2 3]
 [4 5]]


In [ ]:
#Indexing and slicing

data = np.array([1, 2, 3])

print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

2
[1 2]
[2 3]
[2 3]


In [ ]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a[a < 5])
print("\n")
five_up = (a >= 5)
print(a[five_up])
print("\n")
divisible_by_2 = a[a%2==0]
print(divisible_by_2)
print("\n")
c = a[(a > 2) & (a < 11)]
print(c)
print("\n")
five_up = (a > 5) | (a == 5)
print(five_up)

[1 2 3 4]


[ 5  6  7  8  9 10 11 12]


[ 2  4  6  8 10 12]


[ 3  4  5  6  7  8  9 10]


[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [ ]:
#Converting distance in miles to kilometers.

data = np.array([1.0, 2.0])
data * 1.6


array([1.6, 3.2])

In [ ]:
import numpy as np
a = np.array([1.0, 2.0, 3.0])
b = 2.0
a * b

array([2., 4., 6.])

In [ ]:
#Converting distance in miles to kilometers.

data1 = np.array([1.0, 2.0,5, 6])
data2 = np.array([1, 2,3, 4])
data2 * 10
data1 *20

array([ 20.,  40., 100., 120.])

In [ ]:
import numpy as np
arr = np.array([1000,1,10,38,2,56,6,0,-1])
print(arr)
np.sort(arr)

[1000    1   10   38    2   56    6    0   -1]


array([  -1,    0,    1,    2,    6,   10,   38,   56, 1000])

In [ ]:
#numpy.argsort
import numpy as np
arc= np.array([1,2,3])
np.argsort(arc)

array([0, 1, 2])

In [ ]:
#numpy.argsort
import numpy as np
x = np.array([1, 1, 0])
np.argsort(x)

array([2, 0, 1])

In [ ]:
#Indexing and slicing

data = np.array([1, 2, 3,4,5,6])

print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

2
[1 2]
[2 3 4 5 6]
[5 6]
