In [12]:
import numpy as np
nutrient_needs=np.array(
    [
    [128,60,80],
    [158,75,100],
    [100,50,70]
])
fertilizer_composition=np.array(
    [
    [0.20,0.10,0.15],
    [0.15,0.20,0.10],
    [0.10,0.15,0.75]
])
print('nutrient requierments(kg/ha):')
print(nutrient_needs)
print('/fertilizer composition(%):')
print(fertilizer_composition)

total_nutrients_per_crop=np.sum(nutrient_needs,axis=1)
print(f'\nTotal nutrients needed per crop:{total_nutrients_per_crop}kg/ha')

fertilizer_application=np.array([100,180,100])#kg of each type
nutrients_delivered=np.dot(fertilizer_application,fertilizer_composition)
print(f'\nNutrients from 100kg of each type of fertilizer:{nutrients_delivered}')

det=np.linalg.det(fertilizer_composition)
print(f'\nDeterminant of fertilizer composition matrix:{det:6f}')

scaling=np.eye(3) *1.1 #10%increases
enhanced_needs=np.dot(nutrient_needs,scaling)
print('\nEnhanced nutrient needs(10% increase):')
print(enhanced_needs)

nutrient requierments(kg/ha):
[[128  60  80]
 [158  75 100]
 [100  50  70]]
/fertilizer composition(%):
[[0.2  0.1  0.15]
 [0.15 0.2  0.1 ]
 [0.1  0.15 0.75]]

Total nutrients needed per crop:[268 333 220]kg/ha

Nutrients from 100kg of each type of fertilizer:[ 57.  61. 108.]

Determinant of fertilizer composition matrix:0.017125

Enhanced nutrient needs(10% increase):
[[140.8  66.   88. ]
 [173.8  82.5 110. ]
 [110.   55.   77. ]]


In [11]:
import numpy as np
nutrient_needs=np.array(
    [
    [128,60,80],
    [158,75,100],
    [100,50,70]
])
fertilizer_composition=np.array(
    [
    [0.20,0.10,0.15],
    [0.15,0.20,0.10],
    [0.10,0.15,0.75]
])
print('nutrient requierments(kg/ha):')
print(nutrient_needs)
print('/fertilizer composition(%):')
print(fertilizer_composition)

total_nutrients_per_crop=np.sum(nutrient_needs,axis=1)
print(f'\nTotal nutrients needed per crop:{total_nutrients_per_crop}kg/ha')

fertilizer_application=np.array([100,180,100])#kg of each type
nutrients_delivered=np.dot(fertilizer_application,fertilizer_composition)
print(f'\nNutrients from 100kg of each type of fertilizer:{nutrients_delivered}')

det=np.linalg.det(fertilizer_composition)
print(f'\nDeterminant of fertilizer composition matrix:{det:6f}')

scaling=np.eye(3) *1.1 #10%increases
enhanced_needs=np.dot(nutrient_needs,scaling)
print('\nEnhanced nutrient needs(10% increase):')
print(enhanced_needs)

nutrient requierments(kg/ha):
[[128  60  80]
 [158  75 100]
 [100  50  70]]
/fertilizer composition(%):
[[0.2  0.1  0.15]
 [0.15 0.2  0.1 ]
 [0.1  0.15 0.75]]

Total nutrients needed per crop:[268 333 220]kg/ha

Nutrients from 100kg of each type of fertilizer:[ 57.  61. 108.]

Determinant of fertilizer composition matrix:0.017125

Enhanced nutrient needs(10% increase):
[[140.8  66.   88. ]
 [173.8  82.5 110. ]
 [110.   55.   77. ]]
