In [ ]:
import numpy as np
yields=np.array([
    [45,48,52,49,53],
    [38,41,39,44,42],
    [52,55,58,56,60],
    [41,43,45,47,46]
])

weather_factors=np.array([1.0,0.95,1.05,0.98,1.02])
print('original yields(tons/hectare):')
print(yields)
print('\nWeather Impact Factors:',weather_factors)

#broadcasting:
adjusted_yields=yields*weather_factors
print('\nAdjusted Yields(tons/hectare):')
print(adjusted_yields.round(2))

#boolean indexing:
exceptional=adjusted_yields>55
print('\nExceptional Yields(>55):')
print(adjusted_yields[exceptional])

#conditional operations:
categories=np.where(
    adjusted_yields>50,'High',
    np.where(adjusted_yields>40,'Medium','Low')
)
print('\nYield Categories:')
print(categories)

#Advanced indexing:
selected_farms=[0,2] #Farm1 and Farm3
print(f'\nSelected farms yields:')
print(yields[selected_farms])

#Multi-condition filtering:
good_years=adjusted_yields[(adjusted_yields>45)&(adjusted_yields<55)]
print('\nGood performing Years(45-55tons):')
print(good_years)

original yields(tons/hectare):
[[45 48 52 49 53]
 [38 41 39 44 42]
 [52 55 58 56 60]
 [41 43 45 47 46]]

Weather Impact Factors: [1.   0.95 1.05 0.98 1.02]

Adjusted Yields(tons/hectare):
[[45.   45.6  54.6  48.02 54.06]
 [38.   38.95 40.95 43.12 42.84]
 [52.   52.25 60.9  54.88 61.2 ]
 [41.   40.85 47.25 46.06 46.92]]

Exceptional Yields(>55):
[60.9 61.2]

Yield Categories:
[['Medium' 'Medium' 'High' 'Medium' 'High']
 ['Low' 'Low' 'Medium' 'Medium' 'Medium']
 ['High' 'High' 'High' 'High' 'High']
 ['Medium' 'Medium' 'Medium' 'Medium' 'Medium']]

Selected farms yields:
[[45 48 52 49 53]
 [52 55 58 56 60]]

Good performing Years(45-55tons):
[45.6  54.6  48.02 54.06 52.   52.25 54.88 47.25 46.06 46.92]


In [ ]:
import numpy as np
a=np.arange(50).reshape(10,5)
print("original array(10*5):\n",a)

#select all rows where the first festure
# (column 0) is greater than 20
print(a[:])
print(a[:,0])
print(a[:,1])
selected_rows=a[a[:,0]>20]
print("\nRows where first festure>20:\n",selected_rows)


original array(10*5):
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]
[ 0  5 10 15 20 25 30 35 40 45]
[ 1  6 11 16 21 26 31 36 41 46]

Rows where first festure>20:
 [[25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]


In [ ]:
import numpy as np
yields=np.array([
    [45,48,52,49,53],
    [38,41,39,44,42],
    [52,55,58,56,60],
    [41,43,45,47,46]
])

weather_factors=np.array([1.0,0.95,1.05,0.98,1.02])
print('original yields(tons/hectare):')
print(yields)
print('\nWeather Impact Factors:',weather_factors)

#broadcasting:
adjusted_yields=yields*weather_factors
print('\nAdjusted Yields(tons/hectare):')
print(adjusted_yields.round(2))

#boolean indexing:
exceptional=adjusted_yields>55
print('\nExceptional Yields(>55):')
print(adjusted_yields[exceptional])

#conditional operations:
categories=np.where(
    adjusted_yields>50,'High',
    np.where(adjusted_yields>40,'Medium','Low')
)
print('\nYield Categories:')
print(categories)

#Advanced indexing:
selected_farms=[0,2] #Farm1 and Farm3
print(f'\nSelected farms yields:')
print(yields[selected_farms])

#Multi-condition filtering:
good_years=adjusted_yields[(adjusted_yields>45)&(adjusted_yields<55)]
print('\nGood performing Years(45-55tons):')
print(good_years)

original yields(tons/hectare):
[[45 48 52 49 53]
 [38 41 39 44 42]
 [52 55 58 56 60]
 [41 43 45 47 46]]

Weather Impact Factors: [1.   0.95 1.05 0.98 1.02]

Adjusted Yields(tons/hectare):
[[45.   45.6  54.6  48.02 54.06]
 [38.   38.95 40.95 43.12 42.84]
 [52.   52.25 60.9  54.88 61.2 ]
 [41.   40.85 47.25 46.06 46.92]]

Exceptional Yields(>55):
[60.9 61.2]

Yield Categories:
[['Medium' 'Medium' 'High' 'Medium' 'High']
 ['Low' 'Low' 'Medium' 'Medium' 'Medium']
 ['High' 'High' 'High' 'High' 'High']
 ['Medium' 'Medium' 'Medium' 'Medium' 'Medium']]

Selected farms yields:
[[45 48 52 49 53]
 [52 55 58 56 60]]

Good performing Years(45-55tons):
[45.6  54.6  48.02 54.06 52.   52.25 54.88 47.25 46.06 46.92]
