In [10]:
import numpy as np
#NUTRIENT AND FERTILIZER REQUIREMENTS OF 3 CROPS
nutrient_needs=np.array([[12,60,80],[150,75,100],[100,50,70]])
fertilizer_composition=np.array([[0.20,0.10,0.15],[0.15,0.20,0.10],[0.10,0.15,0.25]])
print('nutrient requirements(kg\\ha):')
print(nutrient_needs)
print('\nfertilizer composition(%):')
print(fertilizer_composition)

#MATRIX TRANSPOSE EXAMPLE
print('\n transposed nutrient needs:')
print(nutrient_needs.T)
total_nutrients_per_crop=np.sum(nutrient_needs,axis=1)
print(f'\n total nutrients needs per crop:{total_nutrients_per_crop}kg/ha')

fertilizer_application=np.array([100,100,100])
nutrients_delivered=np.dot(fertilizer_composition,fertilizer_application)
print('\nnutrients_delivered:')
print(nutrients_delivered)

#CALCULATING DETERMINANT FOR MATRIX
det=np.linalg.det(fertilizer_composition)
print(f'\ndeterminant of fertilizer:{det:6f}')

#IDENTITY MATRIX EXAMPLE(SCALING FACTOR)
scaling=np.eye(3)
enhanced_needs=np.dot(nutrient_needs,scaling)
print('\n enhanced nutrient needs(10% increase):')
print(enhanced_needs)

nutrient requirements(kg\ha):
[[ 12  60  80]
 [150  75 100]
 [100  50  70]]

fertilizer composition(%):
[[0.2  0.1  0.15]
 [0.15 0.2  0.1 ]
 [0.1  0.15 0.25]]

 transposed nutrient needs:
[[ 12 150 100]
 [ 60  75  50]
 [ 80 100  70]]

 total nutrients needs per crop:[152 325 220]kg/ha

nutrients_delivered:
[45. 45. 50.]

determinant of fertilizer:0.004625

 enhanced nutrient needs(10% increase):
[[ 12.  60.  80.]
 [150.  75. 100.]
 [100.  50.  70.]]
