In [ ]:
#NUMPY
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
arr=np.array((1,2,3,4,5))
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
arr=np.array(42)
print(arr)

42


In [ ]:
#1-D ARRAY
import numpy as np
arr=np.array((1,2,3,4,5))
print(arr)

[1 2 3 4 5]


In [ ]:
#2-D ARRAY
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr)


[[1 2 3]
 [4 5 6]]


In [ ]:
#3-D ARRAY
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [ ]:
import numpy as numpy
a=np.array(42)
b=np.array((1,2,3,4,5))
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [ ]:
#HIGHER DIMENSIONAL ARRAY
import numpy as np
arr=np.array([1,2,3,4],ndmin=5)
print(arr)
print('number of dimensions:',arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions: 5


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr[0])


1


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr[2]+arr[3])

7


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])
arr_2d=np.array([[[1,2,3],[4,5,6]]])
zeros=np.zeros((3,4))
ones=np.ones((2,3))
range_arr=np.arange(0,10,2)
linspace=np.linspace(0,1,5)
identity=np.eye(3)
random_arr=np.random.rand(3,4)
print(zeros)
print(ones)
print(range_arr)
print(linspace)
print(identity)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
import numpy as np
a=np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a.shape)
print(a.dtype)
print(a.size)
print(a.ndim)
np.sum(a)
np.mean(a,axis=0)
np.mean(a,axis=1)
np.max(a)
np.min(a)
print(sum(a))


(2, 3)
int64
6
2
[5 7 9]


In [68]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
np.mean(a,axis=1)



array([2., 5.])

In [67]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
np.mean(a,axis=0)



array([2.5, 3.5, 4.5])

In [65]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
np.max(a)


np.int64(6)

In [66]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
np.min(a)


np.int64(1)

In [62]:
b=np.array([10,40,30])
np.argmax(b)

np.int64(1)

In [60]:
print("EXAMPLE")

import numpy as np

#crop yields of 4 farms over 5 seasons in tons
crop_yields=np.array([
    [12.5,13.2,14.1,13.8,15.2],
    [10.3,11.5,10.8,12.2,11.9],
    [15.1,14.8,16.2,15.5,16.8],
    [11.2,10.9,12.3,11.7,12.8]
    ])

print('crop yields array(tons):')
print(crop_yields)
print(f'\n Shape:{crop_yields.shape}')
print(f'data type:{crop_yields.dtype}')
print(f'total elements:{crop_yields.size}')
print(f'number of dimensions:{crop_yields.ndim}')

#AGRICULTURAL ANALYSIS OPERATIONS

total_yield=np.sum(crop_yields)
avg_yield_per_farm=np.mean(crop_yields,axis=1)
avg_yield_per_season=np.mean(crop_yields,axis=0)
max_yield=np.max(crop_yields)
min_yield=np.min(crop_yields)

print(f'\n total production:{total_yield}tons')
print(f'average per farm:{avg_yield_per_farm}tons')
print(f'average per season:{avg_yield_per_season}tons')
print(f'maximum yield:{max_yield}tons')
print(f'minimum yield:{min_yield}tons')

#find best performing farm
best_farm_index=np.argmax(avg_yield_per_farm) # Corrected: use avg_yield_per_farm to find best farm index
print(f'\n best performing farm:farm{best_farm_index+1}')
print(f'their average yield:{avg_yield_per_farm[best_farm_index]:.2f}tons')

EXAMPLE
crop yields array(tons):
[[12.5 13.2 14.1 13.8 15.2]
 [10.3 11.5 10.8 12.2 11.9]
 [15.1 14.8 16.2 15.5 16.8]
 [11.2 10.9 12.3 11.7 12.8]]

 Shape:(4, 5)
data type:float64
total elements:20
number of dimensions:2

 total production:262.8tons
average per farm:[13.76 11.34 15.68 11.78]tons
average per season:[12.275 12.6   13.35  13.3   14.175]tons
maximum yield:16.8tons
minimum yield:10.3tons

 best performing farm:farm3
their average yield:15.68tons
